app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [

    path('', include('users.urls')),
    # path('', include("app.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('authn.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('captcha/', include('captcha.urls')),

    # path('axes/', include('axes.urls', namespace='axes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'dashboard.views.custom_404'
handler404 = 'users.views.custom_404'
handler404 = 'authn.views.custom_404'

dashboard/urls.py
from django.urls import path
from .views import (
    index, hemis_arizalar, Ariza_edit,
    lms_arizalar, kero_a_arizalar, admin_profile_view,
    yuklash_sahifasi, fayllar, teacher, get_authors,
    edit_input, fayl_detail, tasdiqlash,
    fayl_tasdiq, kero_c_arizalar, vaucher_arizalar

)

urlpatterns = [
    path('', index, name="index"),
    path('admin/profile/', admin_profile_view, name='admin_profile'),
    path('applications/hemis/', hemis_arizalar, name='hemis_arizalar'),
    path('applications/lms/', lms_arizalar, name='lms_arizalar'),
    path('applications/A-bino/kerio/', kero_a_arizalar, name='kero_a_arizalar'),
    path('applications/C-bino/kerio/', kero_c_arizalar, name='kero_c_arizalar'),
    path('applications/vaucher_arizalar/', vaucher_arizalar, name='vaucher_arizalar'),
    path('application/<int:pk>/edit/', Ariza_edit, name='application_edit'),

    path('admin/fileinput/', yuklash_sahifasi, name='yuklash_sahifasi'),
    path('admin/files/', fayllar, name='files'),
    path('admin/teacher/', teacher, name='teacher'),
    path('get_authors/', get_authors, name='get_authors'),

    path('admin/fileinput//<int:pk>/edit/', edit_input, name='edit_input'),

    path('admin/fayl/', fayl_tasdiq, name='fayl_tasdiq'),
    path('fayl/<int:fayl_id>/', fayl_detail, name='fayl_detail'),
    path('fayl/<int:fayl_id>/tasdiqlash/', tasdiqlash, name='tasdiqlash'),
]

dashboard/models.py
from django.db import models
from users.validators import validate_passport_serial
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.templatetags.static import static
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils import timezone
import os
from users.models import Faculty, Kafedra
from django.db.models.signals import post_save


def admin_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'user_{instance.user.id}/avatar/{filename}'


class AdminProfile(models.Model): 
    is_hemis_admin = models.BooleanField(default=False, null=True, blank=True)
    is_lms_admin = models.BooleanField(default=False, null=True, blank=True)
    is_kerocontrol_admin = models.BooleanField(default=False, null=True, blank=True )
    is_kerocontrol2_admin = models.BooleanField(default=False, null=True, blank=True )
    is_kerocontrol3_admin = models.BooleanField(default=False, null=True, blank=True )
    is_self_visible = models.BooleanField(default=False, null=True, blank=True)
    is_admin = models.BooleanField(default=False, null=True, blank=True)
    is_admin_kafedra = models.BooleanField(default=False, null=True, blank=True)
    is_admin_talim = models.BooleanField(default=False, null=True, blank=True)
    is_admin_oquv = models.BooleanField(default=False, null=True, blank=True)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, gettext("Erkak")),
        (GENDER_FEMALE, gettext("Ayol")),
    ]
    user = models.OneToOneField(User, related_name="admin_profile", on_delete=models.CASCADE)
    admin_avatar = models.ImageField(upload_to="admin/profiles/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = gettext('Profile')
        verbose_name_plural = gettext('Profiles')

    @property
    def get_admin_avatar(self):
        return self.admin_avatar.url if self.admin_avatar else static('img/team/default-profile-picture.png')
 
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Check if this instance has a file already
        try:
            this = AdminProfile.objects.get(id=self.id)
            # If the file exists and is not the same as the new file, delete the old file
            if this.admin_avatar and this.admin_avatar != self.admin_avatar:
                this.admin_avatar.delete(save=False)
        except AdminProfile.DoesNotExist:
            pass

        super(AdminProfile, self).save(*args, **kwargs)


@receiver(post_delete, sender=AdminProfile)
def admin_profile_post_delete_handler(sender, **kwargs):
    admin_profile = kwargs['en']
    # Delete the old file when the associated UserProfile object is deleted
    if admin_profile.admin_avatar:
        admin_profile.admin_avatar.delete(False)


class Author(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    kafedra = models.ForeignKey(Kafedra, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class FileType(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Fayl(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    filetype = models.ForeignKey(FileType, related_name='fayl_type', on_delete=models.SET_NULL, null=True)
    faculty = models.ForeignKey(Faculty, related_name='faculty', on_delete=models.SET_NULL, null=True)
    kafedra = models.ForeignKey(Kafedra, related_name='kafedra', on_delete=models.SET_NULL, null=True)
    authn = models.ManyToManyField(Author, related_name='author', blank=True)
    fayl = models.FileField(upload_to='fayllar/')
    tasdiq_soni = models.IntegerField(null=True, blank=True, default=0)
    tasdiqlangan = models.BooleanField(default=False)
    createdate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
 

class FaylTasdiq(models.Model): 
    fayl = models.ForeignKey(Fayl, on_delete=models.CASCADE)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    tasdiq_vaqt = models.DateTimeField(auto_now_add=True)
    tasdiq_holati = models.BooleanField(default=False, null=True)
    admin_tekshirish_vaqt = models.DateTimeField(null=True, blank=True)
    update = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=FaylTasdiq)
def avtomatik_tekshirish_vaqt(sender, instance, created, **kwargs):
    if created and not instance.tasdiq_holati:
        instance.tasdiq_holati = True
        instance.admin_tekshirish_vaqt = timezone.now()
        instance.save()

users/models.py
from django.db import models
from .validators import validate_passport_serial
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.templatetags.static import static
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils import timezone
import os


def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'user_{instance.user.id}/avatar/{filename}'


class Profile(models.Model): 
    is_users = models.BooleanField(default=True, null=True, blank=True)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, gettext("Erkak")),
        (GENDER_FEMALE, gettext("Ayol")),
    ]
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="user/profiles/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = gettext('Profile')
        verbose_name_plural = gettext('Profiles')

    @property
    def get_avatar(self):
        return self.avatar.url if self.avatar else static('img/team/default-profile-picture.png')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Check if this instance has a file already
        try:
            this = Profile.objects.get(id=self.id)
            # If the file exists and is not the same as the new file, delete the old file
            if this.avatar and this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except Profile.DoesNotExist:
            pass

        super(Profile, self).save(*args, **kwargs)


@receiver(post_delete, sender=Profile)
def user_profile_post_delete_handler(sender, **kwargs):
    user_profile = kwargs['instance']
    # Delete the old file when the associated UserProfile object is deleted
    if user_profile.avatar:
        user_profile.avatar.delete(False)


class Faculty(models.Model):  # 1-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Kafedra(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Position(models.Model):  # 2-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class System(models.Model):  # 4-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Talimshakli(models.Model):
    name = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.name


class PositionOne(models.Model):
    name = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        return self.name


class Building(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

class LoginCreate(models.Model):
    name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name


class Application(models.Model):
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)

    passport_image = models.ImageField(upload_to='user_passport/', null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, blank=True)

    login_create = models.ForeignKey(LoginCreate, on_delete=models.SET_NULL, null=True, blank=True) 
    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    group = models.CharField(max_length=50, null=True, blank=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    talim_shakli = models.ForeignKey(Talimshakli, on_delete=models.SET_NULL, null=True, blank=True)

    kafedra = models.ForeignKey(Kafedra, on_delete=models.SET_NULL, null=True, blank=True)
    positionone = models.ForeignKey(PositionOne, on_delete=models.SET_NULL, null=True, blank=True) 

    tizim = models.CharField(max_length=50, null=True, blank=True)
    building = models.ForeignKey(Building, on_delete=models.SET_NULL, null=True, blank=True)

    text = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']

    @property
    def get_passport(self):
        return self.passport_image.url if self.passport_image else static('')


    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ApplicationCreate(models.Model): 
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    application = models.OneToOneField(Application,  related_name='app_create', on_delete=models.SET_NULL, null=True, blank=True) 
    update = models.DateTimeField(auto_now=True)
    createdate = models.DateTimeField(auto_now_add=True)

    body = models.TextField(null=True, blank=True, default='Yo\'q')
    STATUS_CHOICES = (
        ('yangi', 'Yangi'),
        ('tekshirilmoqda', 'Tekshirilmoqda'),
        ('rad etildi', 'Rad etildi'),
        ('tekshirildi', 'Tekshirildi'),
    )
    status = models.CharField(max_length=14, choices=STATUS_CHOICES, default='yangi', null=True)

    class Meta:
        ordering = ['-update', '-createdate']

    def __str__(self):
        return self.user.username if self.user else 'Foydalanuvchi yuq'

dashboard/forms.py
from django import forms
from users.models import ApplicationCreate, Application
from .models import AdminProfile, Fayl, Author, FaylTasdiq


class ApplicationCreateForm(forms.ModelForm):
    class Meta: 
        model = ApplicationCreate
        fields = "__all__"
        widgets = {
            "status": forms.Select(attrs={'class': 'form-control'}),
            "user": forms.Select(attrs={'class': 'form-control', 'readonly': True}),
            "application": forms.Select(attrs={'class': 'form-control', 'readonly': True}),
         }

 
class AdminProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField()

    class Meta:
        model = AdminProfile
        fields = '__all__'
        exclude = ['user']

    def clean_email(self):
        email = self.cleaned_data['email']
        if "example.com" in email:
            raise forms.ValidationError("Example.com manzilini ishlatmaslik kerak")
        return email


class FaylInputForm(forms.ModelForm):
    class Meta:
        model = Fayl
        fields = '__all__'
        widgets = {
            "user": forms.Select(attrs={'class': 'form-control'}),
            "faculty": forms.Select(attrs={'class': 'form-control'}),
            "kafedra": forms.Select(attrs={'class': 'form-control'}),
            "authn": forms.SelectMultiple(attrs={'class': 'form-control'}),
            "filetype": forms.Select(attrs={'class': 'form-control'}),
            "fayl": forms.FileInput(attrs={'class': 'form-control', 'id':'fayl', "accept":".pdf"}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FaylInputForm, self).__init__(*args, **kwargs)
        if user and self.instance:
            self.fields['user'].initial = user
            self.fields['kafedra'].initial = self.instance.kafedra


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}),
            "kafedra": forms.Select(attrs={'class': 'form-control'}),
        }

templates/admins/admin/ariza_edit.html
{% extends "admins/admin/base.html" %}
{% load static %}
{% block content %}

  

    <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_settings-panel.html -->
        <div class="theme-setting-wrapper">
          <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
          <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">Yon paneldagi terilar</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
              <div class="img-ss rounded-circle bg-light border mr-3"></div>
              Oq
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
              <div class="img-ss rounded-circle bg-dark border mr-3"></div>
              Qora
            </div>
            <p class="settings-heading mt-2">SARLIK TERILARI</p>
            <div class="color-tiles mx-0 px-4">
              <div class="tiles success"></div>
              <div class="tiles warning"></div>
              <div class="tiles danger"></div>
              <div class="tiles primary"></div>
              <div class="tiles info"></div>
              <div class="tiles dark"></div>
              <div class="tiles default border"></div>
            </div>
          </div>
        </div>
        {% include 'admins/admin/sidbare.html' %}
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="card-body">
                        <h1 class="text-center">{{application}}</h1>
                    </div>
                </div>
                <div class="col-md-12 grid-margin stretch-card">
                        <div class="card mb-3" style="max-width: 540px;">
                            <div class="row g-0">
                                <div class="col-md-5">
                                    <div class="card-body">
                                        <a target="_blank" href="{{ application.get_passport }}">
                                        <img src="{{ application.get_passport }}" class="img-fluid rounded-start" alt="rasm" style="border-radius: 8%;">
                                    </a>
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="card-body">
                                        {% if application.login_create.id == 1 %}
                                        <p class="text"><b>Murojaat turi:</b> {{application.login_create}}</p>
                                        <p class="text"><b>Bino:</b>{{application.building}}</p>
                                        <p class="text"><b>Login:</b>{{application.name}}</p>
                                        <p class="text"><b>Telefon:</b> +{{application.phone}}  </p>
                                        <p class="text"><b>Passvor seria:</b> {{application.passport_serial}}</p>
                                        <p class="text"><b>Email:</b> {{application.user.email}}</p>
                                        <p class="text"><b>{{application.first_name}}ning arizaga izohi: </b>{{application.text}}</p>
                                        {% elif application.login_create.id == 2 %}
                                        <p class="text"><b>Murojaat turi:</b> {{application.login_create}}</p>
                                        <p class="text"><b>Guruh:</b> {{application.group}}</p>
                                        <p class="text"><b>Telefon:</b> +{{application.phone}}  </p>
                                        <p class="text"><b>Passvor seria:</b> {{application.passport_serial}}</p>
                                        <p class="text"><b>Email:</b> {{application.user.email}}</p>
                                        <p class="text"><b>{{application.first_name}}ning arizaga izohi: </b>{{application.text}}</p>
                                        {% elif application.login_create.id == 3 %}
                                        <p class="text"><b>Murojaat turi:</b> {{application.login_create}}</p>
                                        {% if application.system.id == 1 or application.system.id == 2 %}
                                        <p class="text"><b>Tizim:</b> {{application.system}}</p>
                                        <p class="text"><b>Id/login:</b>{{application.tizim}}</p>
                                        {% elif application.system.id == 3 %}
                                        <p class="text"><b>Tizim:</b> {{application.system}}</p>
                                        <p class="text"><b>Id/login:</b>{{application.tizim}}</p>
                                        <p class="text"><b>Bino:</b>{{application.building}}</p>
                                        {% endif %}
                                        <p class="text"><b>Telefon:</b> +{{application.phone}}  </p>
                                        <p class="text"><b>Passvor seria:</b> {{application.passport_serial}}</p>
                                        <p class="text"><b>Email:</b> {{application.user.email}}</p>
                                        <p class="text"><b>{{application.first_name}}ning arizaga izohi: </b>{{application.text}}</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-md-5">
                                </div>
                                <div class="col-md-7">
                                    <div class="card-body">
                                        {% if application.position.id == 1 %}
                                        <p class="text"><b>Lavozim:</b> {{application.position}}</p>
                                        <p class="text"><b>Fakultet:</b> {{application.faculty}}</p>
                                        <p class="text"><b>Ta'lim shakli:</b> {{application.talim_shakli}}</p>
                                        <p class="text"><b>Tug'ulgan sana:</b> {{application.birthday}}</p>
                                        <p class="text"><b>Ariza holati:</b> <small class="h5" style="color: blue;">{{application.app_create.status}}</small></p>
                                        <p class="text"><b>Admin izohi:</b> <small class="h5" style="color: blue;">{{application.app_create.body}}</small></p>
                                        {% elif application.position.id == 2 %}
                                        <p class="text"><b>Lavozim:</b> {{application.position}}</p>
                                        <p class="text"><b>Kafedra:</b> {{application.kafedra}}</p>
                                        <p class="text"><b>Tug'ulgan sana:</b> {{application.birthday}}</p>
                                        <p class="text"><b>Ariza holati:</b> <small class="h5" style="color: blue;">{{application.app_create.status}}</small></p>
                                        <p class="text"><b>Admin izohi:</b> <small class="h5" style="color: blue;">{{application.app_create.body}}</small></p>
                                        {% elif application.position.id == 3 %}
                                        <p class="text"><b>Lavozim:</b> {{application.position}}</p>
                                        <p class="text"><b>Bolim:</b> {{application.positionone}}</p>
                                        <p class="text"><b>Tug'ulgan sana:</b> {{application.birthday}}</p>
                                        <p class="text"><b>Ariza holati:</b> <small class="h5" style="color: blue;">{{application.app_create.status}}</small></p>
                                        <p class="text"><b>Admin izohi:</b> <small class="h5" style="color: blue;">{{application.app_create.body}}</small></p>
                                        {% endif %}
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="col-md-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                    <div class="row"> 
                                        <div class="col-md-4">
                                            <div class="form-group row">
                                            <label for="status">Status:</label>
                                            {{form.status}}
                                        </div>
                                        </div>
                                        <div class="col-md-4" hidden>
                                            <label for="status">Username:</label>
                                            {{form.user}}
                                        </div>
                                        <div class="col-md-4" hidden>
                                            <label for="status">Ism Familiya:</label>
                                            {{form.application}}
                                        </div>
                                        
                                    </div> <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group row">
                                            <label for="id_body">Murojaat mazmuni to'liq xolda</label>
                                            <textarea name="body" class="form-control" id="id_body" style="height:155px" required ></textarea>
                                        </div>
                                        </div>
                                    </div><br>
                                    <button type="submit" class="save btn btn-secondary">Saqlash</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
          </div>
          <!-- content-wrapper ends -->
          {% include 'users/admins/footer.html' %}
        </div>
        <!-- main-panel ends -->
    </div>
   
{% endblock content %}

templates/admins/admin/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TATU Samarqand filiali</title>
    <!-- base:css -->
    <link rel="stylesheet" href="{% static 'admin/vendors/typicons.font/font/typicons.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject --> 
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'admin/css/vertical-layout-light/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/mdi/css/materialdesignicons.min.css' %}">
    <!-- endinject -->
     <link rel="shortcut icon" href="{% static 'img/illustrations/Logo.png' %}" />
     <!-- endinject -->
     <link rel="stylesheet" href="{% static 'admin/vendors/select2/select2.min.css' %}">
     <link rel="stylesheet" href="{% static 'admin/vendors/select2-bootstrap-theme/select2-bootstrap.min.css' %}">
     <!-- End plugin css for this page -->
    <link rel="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

</head>
<body>
    {% include 'notification.html' %}
    <div class="row" id="proBanner" hidden>
        
        <div class="col-12">
            <i class="typcn typcn-delete-outline" id="bannerClose"></i>
        </div>
    </div>
    <div class="container-scroller">

        {% include 'admins/admin/navbar.html' %}

        {% block content %}

        {% endblock content %}
    </div>
<!-- container-scroller -->
    <!-- base:js -->
    <script src="{% static 'admin/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="{% static 'admin/js/off-canvas.js' %}"></script>
    <script src="{% static 'admin/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'admin/js/template.js' %}"></script>
    <script src="{% static 'admin/js/settings.js' %}"></script>
    <script src="{% static 'admin/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{% static 'admin/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'admin/vendors/chart.js/Chart.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="{% static 'admin/js/dashboard.js' %}"></script>
    <!-- End custom js for this page-->

  <!-- endinject -->
  <!-- plugin js for this page -->
  <script src="{% static 'admin/vendors/typeahead.js/typeahead.bundle.min.js' %}"></script>
  <script src="{% static 'admin/vendors/select2/select2.min.js' %}"></script>
  <!-- End plugin js for this page -->
  <!-- Custom js for this page-->
  <script src="{% static 'admin/js/file-upload.js' %}"></script>
  <script src="{% static 'admin/js/typeahead.js' %}"></script>
  <script src="{% static 'admin/js/select2.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>