app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [

    path('', include('users.urls')),
    # path('', include("app.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('authn.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('captcha/', include('captcha.urls')),

    # path('axes/', include('axes.urls', namespace='axes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'dashboard.views.custom_404'
handler404 = 'users.views.custom_404'
handler404 = 'authn.views.custom_404'

dashboard/models.py
from django.db import models
from users.validators import validate_passport_serial
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.templatetags.static import static
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils import timezone
import os
from users.models import Faculty, Kafedra
from django.db.models.signals import post_save


def admin_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'user_{instance.user.id}/avatar/{filename}'


class AdminProfile(models.Model): 
    is_hemis_admin = models.BooleanField(default=False, null=True, blank=True)
    is_lms_admin = models.BooleanField(default=False, null=True, blank=True)
    is_kerocontrol_admin = models.BooleanField(default=False, null=True, blank=True )
    is_kerocontrol2_admin = models.BooleanField(default=False, null=True, blank=True )
    is_kerocontrol3_admin = models.BooleanField(default=False, null=True, blank=True )
    is_self_visible = models.BooleanField(default=False, null=True, blank=True)
    is_admin = models.BooleanField(default=False, null=True, blank=True)
    is_admin_kafedra = models.BooleanField(default=False, null=True, blank=True)
    is_admin_talim = models.BooleanField(default=False, null=True, blank=True)
    is_admin_oquv = models.BooleanField(default=False, null=True, blank=True)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, gettext("Erkak")),
        (GENDER_FEMALE, gettext("Ayol")),
    ]
    user = models.OneToOneField(User, related_name="admin_profile", on_delete=models.CASCADE)
    admin_avatar = models.ImageField(upload_to="admin/profiles/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = gettext('Profile')
        verbose_name_plural = gettext('Profiles')

    @property
    def get_admin_avatar(self):
        return self.admin_avatar.url if self.admin_avatar else static('img/team/default-profile-picture.png')
 
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Check if this instance has a file already
        try:
            this = AdminProfile.objects.get(id=self.id)
            # If the file exists and is not the same as the new file, delete the old file
            if this.admin_avatar and this.admin_avatar != self.admin_avatar:
                this.admin_avatar.delete(save=False)
        except AdminProfile.DoesNotExist:
            pass

        super(AdminProfile, self).save(*args, **kwargs)


@receiver(post_delete, sender=AdminProfile)
def admin_profile_post_delete_handler(sender, **kwargs):
    admin_profile = kwargs['en']
    # Delete the old file when the associated UserProfile object is deleted
    if admin_profile.admin_avatar:
        admin_profile.admin_avatar.delete(False)


class Author(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    kafedra = models.ForeignKey(Kafedra, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class FileType(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Fayl(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    filetype = models.ForeignKey(FileType, related_name='fayl_type', on_delete=models.SET_NULL, null=True)
    faculty = models.ForeignKey(Faculty, related_name='faculty', on_delete=models.SET_NULL, null=True)
    kafedra = models.ForeignKey(Kafedra, related_name='kafedra', on_delete=models.SET_NULL, null=True)
    authn = models.ManyToManyField(Author, related_name='author', blank=True)
    fayl = models.FileField(upload_to='fayllar/')
    tasdiq_soni = models.IntegerField(null=True, blank=True, default=0)
    tasdiqlangan = models.BooleanField(default=False)
    createdate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
 

class FaylTasdiq(models.Model): 
    fayl = models.ForeignKey(Fayl, on_delete=models.CASCADE)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    tasdiq_vaqt = models.DateTimeField(auto_now_add=True)
    tasdiq_holati = models.BooleanField(default=False, null=True)
    admin_tekshirish_vaqt = models.DateTimeField(null=True, blank=True)
    update = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=FaylTasdiq)
def avtomatik_tekshirish_vaqt(sender, instance, created, **kwargs):
    if created and not instance.tasdiq_holati:
        instance.tasdiq_holati = True
        instance.admin_tekshirish_vaqt = timezone.now()
        instance.save()

users/models.py
from django.db import models
from .validators import validate_passport_serial
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.templatetags.static import static
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils import timezone
import os


def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'user_{instance.user.id}/avatar/{filename}'


class Profile(models.Model): 
    is_users = models.BooleanField(default=True, null=True, blank=True)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, gettext("Erkak")),
        (GENDER_FEMALE, gettext("Ayol")),
    ]
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="user/profiles/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = gettext('Profile')
        verbose_name_plural = gettext('Profiles')

    @property
    def get_avatar(self):
        return self.avatar.url if self.avatar else static('img/team/default-profile-picture.png')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Check if this instance has a file already
        try:
            this = Profile.objects.get(id=self.id)
            # If the file exists and is not the same as the new file, delete the old file
            if this.avatar and this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except Profile.DoesNotExist:
            pass

        super(Profile, self).save(*args, **kwargs)


@receiver(post_delete, sender=Profile)
def user_profile_post_delete_handler(sender, **kwargs):
    user_profile = kwargs['instance']
    # Delete the old file when the associated UserProfile object is deleted
    if user_profile.avatar:
        user_profile.avatar.delete(False)


class Faculty(models.Model):  # 1-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Kafedra(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Position(models.Model):  # 2-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class System(models.Model):  # 4-model
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Talimshakli(models.Model):
    name = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.name


class PositionOne(models.Model):
    name = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        return self.name


class Building(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

class LoginCreate(models.Model):
    name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name


class Application(models.Model):
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    passport_serial = models.CharField(max_length=9, validators=[validate_passport_serial], null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)

    passport_image = models.ImageField(upload_to='user_passport/', null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, blank=True)

    login_create = models.ForeignKey(LoginCreate, on_delete=models.SET_NULL, null=True, blank=True) 
    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    group = models.CharField(max_length=50, null=True, blank=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    talim_shakli = models.ForeignKey(Talimshakli, on_delete=models.SET_NULL, null=True, blank=True)

    kafedra = models.ForeignKey(Kafedra, on_delete=models.SET_NULL, null=True, blank=True)
    positionone = models.ForeignKey(PositionOne, on_delete=models.SET_NULL, null=True, blank=True) 

    tizim = models.CharField(max_length=50, null=True, blank=True)
    building = models.ForeignKey(Building, on_delete=models.SET_NULL, null=True, blank=True)

    text = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']

    @property
    def get_passport(self):
        return self.passport_image.url if self.passport_image else static('')


    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ApplicationCreate(models.Model): 
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    application = models.OneToOneField(Application,  related_name='app_create', on_delete=models.SET_NULL, null=True, blank=True) 
    update = models.DateTimeField(auto_now=True)
    createdate = models.DateTimeField(auto_now_add=True)

    body = models.TextField(null=True, blank=True, default='Yo\'q')
    STATUS_CHOICES = (
        ('yangi', 'Yangi'),
        ('tekshirilmoqda', 'Tekshirilmoqda'),
        ('rad etildi', 'Rad etildi'),
        ('tekshirildi', 'Tekshirildi'),
    )
    status = models.CharField(max_length=14, choices=STATUS_CHOICES, default='yangi', null=True)

    class Meta:
        ordering = ['-update', '-createdate']

    def __str__(self):
        return self.user.username if self.user else 'Foydalanuvchi yuq'

templates/admins/fayl/detail.html
{% extends "admins/admin/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_settings-panel.html -->
    <div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
        <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">Yon paneldagi terilar</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
                <div class="img-ss rounded-circle bg-light border mr-3"></div>
                Oq
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                Qora
            </div>
            <p class="settings-heading mt-2">SARLIK TERILARI</p>
            <div class="color-tiles mx-0 px-4">
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles primary"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default border"></div>
            </div>
        </div>
    </div>
    {% include 'admins/admin/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-md-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title"><a href="">{{ fayl.fayl.name }}</a> </h4>
                            <p class="card-description">Tasdiq soni: {{ fayl.tasdiq_soni }}</p>
                            <p class="card-description">Tasdiqlangan: {% if fayl.tasdiqlangan %} Ha
                                {% else %} Yo'q {% endif %}</p>

                            <div class="row">
                                <div class="col-md-6">
                                    <form method="post" action="{% url 'tasdiqlash' fayl.id %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <div class="form-check form-check-success">
                                                <label class="form-check-label" for="tasdiq_ha">
                                                    <input class="form-check-input" type="radio" id="tasdiq_ha"
                                                           name="tasdiq_holati" value="True" required>
                                                    Tasdiqlash
                                                    <i class="input-helper"></i></label>
                                            </div>
                                            <div class="form-check form-check-primary">
                                                <label class="form-check-label" for="tasdiq_yoq">
                                                    <input class="form-check-input" type="radio" id="tasdiq_yoq"
                                                           name="tasdiq_holati" value="False" required>
                                                    Inkor qilish
                                                    <i class="input-helper"></i></label>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-secondary">Secondary</button>
                                    </form>
                                </div>
                                <div class="col-md-6">

                                    <h3>Tasdiqlar</h3>
                                    <ul>
                                        {% for tasdiq in tasdiqlar %}
                                        <li>
                                            {{ tasdiq.admin.username }} - {{ tasdiq.tasdiq_vaqt }} -
                                            {% if tasdiq.tasdiq_holati %} Tasdiqlandi {% else %} Inkor qilindi
                                            {% endif %}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'users/admins/footer.html' %}
    </div>
    <!-- main-panel ends -->
</div>

{% endblock content %}

templates/admins/fayl/fayl_already_approved.html
{% extends "admins/admin/base.html" %}
{% load static %}
{% block content %}


<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_settings-panel.html -->
    <div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
        <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">Yon paneldagi terilar</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
                <div class="img-ss rounded-circle bg-light border mr-3"></div>
                Oq
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                Qora
            </div>
            <p class="settings-heading mt-2">SARLIK TERILARI</p>
            <div class="color-tiles mx-0 px-4">
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles primary"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default border"></div>
            </div>
        </div>
    </div>
    {% include 'admins/admin/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">

                <h2>Fayl allaqachon tasdiqlangan</h2>
                <p>Uzur, siz bu faylni allaqachon tasdiqladingiz. Siz boshqa harakat qila olmaysiz.</p>


            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'users/admins/footer.html' %}
    </div>
    <!-- main-panel ends -->
</div>

{% endblock content %}

templates/admins/fayl/fayl_input.html
{% extends "admins/admin/base.html" %}
{% load static %}
{% block content %}
<style>
    .label{
    padding:3px;
    border: red;
    }
 .drop-container {
  position: relative;
  display: flex;
  gap: 10px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100px;
  padding: 20px;
  border-radius: 10px;
  border: 2px dashed #555;
  color: #444;
  cursor: pointer;
  transition: background .2s ease-in-out, border .2s ease-in-out;
}

.drop-container:hover {
  background: #eee;
  border-color: #111;
}

.drop-container:hover .drop-title {
  color: #222;
}

.drop-title {
  color: #444;
  font-size: 20px;
  font-weight: bold;
  text-align: center;
  transition: color .2s ease-in-out;
}

  .hidden {
      display: none;
  }
  .hidden1 {
      display: none;
  }

</style>

<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_settings-panel.html -->
    <div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
        <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">Yon paneldagi terilar</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
                <div class="img-ss rounded-circle bg-light border mr-3"></div>
                Oq
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                Qora
            </div>
            <p class="settings-heading mt-2">SARLIK TERILARI</p>
            <div class="color-tiles mx-0 px-4">
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles primary"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default border"></div>
            </div>
        </div>
    </div>
    {% include 'admins/admin/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Fayl yuklash</h4>
                            {% if request.user.admin_profile.is_admin_kafedra or request.user.admin_profile.is_self_visible %}
                            <form class="form-sample" method="post" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label class="">Fakultet</label>
                                            {{ form.faculty }}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label class="">Kafedra</label>
                                            {{ form.kafedra }}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label class="">Fayl turi</label>
                                            {{ form.filetype }}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label class="">Mu'aliflar</label>
                                            <a href="{% url 'teacher' %}" class="link-underline-light"><b
                                                    class="py-2 btn-sm">+</b></a>
                                            {{form.authn}}
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>Fayl yuklash</label>
                                        <div class="form-group row">
                                            <label class="drop-container">
                                                {{ form.fayl }}
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-4" hidden>
                                        <label>Username</label><br>
                                            {{forms.user}}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary">Saqlash</button>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'users/admins/footer.html' %}
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (){
       $('#id_kafedra').change(function () {
           var kafedra_id = $(this).val();
           if (kafedra_id) {
               $.ajax({
                   type: 'GET',
                   url: '{% url "get_authors" %}',
                   data: {'kafedra_id': kafedra_id},
                   success: function (data) {
                       $('#id_authn').empty();
                       $.each(data.authors, function (key, value) {
                           $('#id_authn').append('<option value="' + value.id + '">' + value.name + '</option>');
                       });
                       $('#id_authn').trigger('change');

                       // Avtorlarni avtomatik ravishda tanlash
                       $.each(data.selected_authors, function (key, value) {
                           $('#id_authn option[value="' + value.id + '"]').prop('selected', true);
                       });

                       $('#id_authn').trigger('change');
                   }
               });
           }
       });

       $('#id_authn').select2();
   });
</script>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
{% endblock content %}

templates/admins/fayl/fayl_tasdiq.html
{% extends "admins/admin/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_settings-panel.html -->
    <div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
        <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">Yon paneldagi terilar</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
                <div class="img-ss rounded-circle bg-light border mr-3"></div>
                Oq
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                Qora
            </div>
            <p class="settings-heading mt-2">SARLIK TERILARI</p>
            <div class="color-tiles mx-0 px-4">
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles primary"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default border"></div>
            </div>
        </div>
    </div>
    {% include 'admins/admin/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Yuklangan fayllar</h4>
                            <p class="card-description">
                            </p>
                            <div class="table-responsive">
                                {% if request.user.admin_profile.is_self_visible or request.user.admin_profile.is_admin_talim or request.user.admin_profile.is_admin_oquv %}
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>
                                            Fayl
                                        </th>
                                        <th>
                                            Faylturi
                                        </th>
                                        <th>
                                            Fakultet
                                        </th>
                                        <th>
                                            Kafedra
                                        </th>
                                        <th>
                                            Yuklangan vaqt
                                        </th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% if fayl %}
                                    {% for i in fayl %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'fayl_detail' fayl_id=i.id %}">{{ i.fayl }}</a>
                                        </td>
                                        <td>
                                            {{ i.filetype }}
                                        </td>
                                        <td>
                                            {{ i.faculty }}
                                        </td>
                                        <td>
                                            {{ i.kafedra }}
                                        </td>
                                        <td>
                                            {{i.createdate}}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <p>Hozircha fayllar mavjud emas.</p>
                                    {% endif %}
                                    </tbody>


                                </table>

                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'users/admins/footer.html' %}
    </div>
    <!-- main-panel ends -->
</div>


{% endblock content %}